sudo: required

language: python

matrix:
  include:
    - python: "2.7"
      env: TOX=py27
    - python: "3.6"
      env: TOX=py36
    - python: "3.7"
      env: TOX=py37
    - python: "3.6"
      env: TOX=no


services:
- docker
python:
- 3.6
dist: trusty
stages:
- test
jobs:
  include:
    - name: Windows
      os: windows
      language: sh
      before_install:
        - choco install python3 --version 3.6.8
        - export PATH="/c/Python36:/c/Python36/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel pytest tox
      script:
        - tox -e py36
    - name: Python36
      python: 3.6
      before_install:
        - python -m pip install --upgrade pip wheel pytest tox
      script:
        - tox -e py36
    - name: Python37
      python: 3.7
      before_install:
        - python -m pip install --upgrade pip wheel pytest tox
      script:
        - tox -e py37

cache:
  directories:
  - $HOME/.cache/pip
